export const COMPANY_NAME = "AJC Renovations";
export const PHONE = "(561) 756-6224";
export const EMAIL = "info@ajcrenovations.com";

export const SERVICE_AREAS = [
  "Jupiter",
  "Jupiter Farms",
  "Lantana",
  "Westlake",
  "Greenacres",
  "Wellington",
  "Delray Beach",
  "Boynton Beach",
  "West Palm Beach",
  "Royal Palm Beach",
  "Palm Beach Gardens",
  "Palm Beach",
] as const;

export const SERVICES = [
  {
    name: "Kitchen Renovation",
    slug: "kitchen-renovation",
    shortDescription: "Transform your kitchen into the heart of your home with custom cabinetry, countertops, and modern layouts.",
    description: "Your kitchen is the heart of your home, and AJC Renovations brings expert craftsmanship to every kitchen renovation project across Palm Beach County. From custom cabinetry and premium countertops to modern layouts and energy-efficient appliances, we handle every detail. Whether you want a complete kitchen overhaul or targeted upgrades, our team delivers stunning results that increase your home's value and improve your daily life.",
    features: [
      "Custom cabinetry design & installation",
      "Granite, quartz & marble countertops",
      "Kitchen island construction",
      "Backsplash tile installation",
      "Lighting & electrical upgrades",
      "Plumbing fixture updates",
      "Flooring replacement",
      "Open concept conversions",
    ],
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80",
  },
  {
    name: "Bathroom Renovation",
    slug: "bathroom-renovation",
    shortDescription: "Create a spa-like retreat with updated fixtures, tile work, and modern bathroom designs.",
    description: "Upgrade your bathroom into a relaxing retreat with AJC Renovations. Our Palm Beach County bathroom renovation services cover everything from walk-in showers and freestanding tubs to custom vanities and elegant tile work. We focus on combining beauty with functionality, ensuring your new bathroom meets your lifestyle needs while adding lasting value to your home.",
    features: [
      "Walk-in shower installation",
      "Bathtub replacement & refinishing",
      "Custom vanity & storage solutions",
      "Tile flooring & wall installation",
      "Lighting & ventilation upgrades",
      "Plumbing updates & fixture installation",
      "Accessibility modifications",
      "Water-resistant finishing",
    ],
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1600&q=80",
  },
  {
    name: "Floor Renovation",
    slug: "floor-renovation",
    shortDescription: "Upgrade your flooring with hardwood, tile, vinyl, or laminate installed by experienced professionals.",
    description: "Beautiful floors set the foundation for every room in your home. AJC Renovations provides expert floor renovation services throughout Palm Beach County, including hardwood, tile, luxury vinyl plank, and laminate installation. We handle subfloor preparation, removal of existing flooring, and precise installation to ensure your new floors look perfect and last for years to come.",
    features: [
      "Hardwood floor installation & refinishing",
      "Ceramic & porcelain tile installation",
      "Luxury vinyl plank (LVP) flooring",
      "Laminate flooring installation",
      "Subfloor repair & preparation",
      "Grout & tile repair",
      "Baseboard & trim installation",
      "Waterproof flooring solutions",
    ],
    image: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1622452242370-45b8035e105e?w=1600&q=80",
  },
  {
    name: "Indoor Painting",
    slug: "indoor-painting",
    shortDescription: "Refresh your interior with professional painting services using premium paints and expert techniques.",
    description: "A fresh coat of paint transforms any room instantly. AJC Renovations delivers professional indoor painting services across Palm Beach County with meticulous preparation, premium paints, and clean, sharp results. From accent walls and full room painting to trim work and ceiling refinishing, we protect your furnishings and deliver beautiful, lasting finishes.",
    features: [
      "Full room & whole-home painting",
      "Accent wall design & painting",
      "Trim, baseboard & crown molding painting",
      "Ceiling painting & texturing",
      "Cabinet painting & refinishing",
      "Color consultation",
      "Surface preparation & priming",
      "Low-VOC & eco-friendly paint options",
    ],
    image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=1600&q=80",
  },
  {
    name: "Outdoor Painting",
    slug: "outdoor-painting",
    shortDescription: "Protect and beautify your home's exterior with durable, weather-resistant painting solutions.",
    description: "Palm Beach County's climate demands quality exterior painting that can withstand the heat, humidity, and storms. AJC Renovations uses premium, weather-resistant paints and thorough surface preparation to protect and beautify your home's exterior. From stucco and siding to fences and decks, we ensure a lasting, professional finish that boosts curb appeal.",
    features: [
      "Full exterior home painting",
      "Stucco & siding painting",
      "Deck & patio painting/staining",
      "Fence & gate painting",
      "Pressure washing & surface prep",
      "Trim & shutter painting",
      "Weather-resistant coating application",
      "Color matching & consultation",
    ],
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80",
  },
  {
    name: "Drywall",
    slug: "drywall",
    shortDescription: "Expert drywall installation, repair, and finishing for seamless walls and ceilings.",
    description: "Whether you need new drywall installation, water damage repair, or seamless patching, AJC Renovations has you covered throughout Palm Beach County. Our skilled team handles everything from hanging and taping to texturing and finishing, ensuring smooth, flawless walls and ceilings that are ready for paint or wallpaper.",
    features: [
      "New drywall installation",
      "Drywall repair & patching",
      "Water damage restoration",
      "Tape, mud & finishing",
      "Texture matching & application",
      "Ceiling repair & installation",
      "Soundproofing drywall",
      "Popcorn ceiling removal",
    ],
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1600&q=80",
  },
  {
    name: "Pool Enclosure Restoration",
    slug: "pool-enclosure-restoration",
    shortDescription: "Restore your pool enclosure to like-new condition with screen replacement, frame repair, and structural upgrades.",
    description: "South Florida's weather takes a toll on pool enclosures — from sun damage and corrosion to storm impacts and worn-out screens. AJC Renovations provides expert pool enclosure restoration services throughout Palm Beach County. We repair and replace damaged screens, restore corroded or faded aluminum frames, reinforce structural components, and upgrade hardware to keep your pool area protected, beautiful, and bug-free for years to come.",
    features: [
      "Full screen rescreening & replacement",
      "Aluminum frame repair & restoration",
      "Corrosion treatment & prevention",
      "Storm damage repair",
      "Door & hardware replacement",
      "Structural reinforcement",
      "Frame painting & refinishing",
      "New enclosure installation",
    ],
    image: "https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1572331165267-854da2b021b1?w=1600&q=80",
  },
] as const;
